// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: rts_link

#include "../ui.h"

void ui_about_screen_screen_init(void)
{
    ui_about_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_about_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_about_screen, &ui_img_image_tree_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_about_title = lv_label_create(ui_about_screen);
    lv_obj_set_width(ui_about_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_about_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_about_title, 0);
    lv_obj_set_y(ui_about_title, 10);
    lv_obj_set_align(ui_about_title, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_about_title, "About");
    lv_obj_set_style_text_color(ui_about_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_about_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_about_text = lv_label_create(ui_about_screen);
    lv_obj_set_width(ui_about_text, 200);
    lv_obj_set_height(ui_about_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_about_text, 0);
    lv_obj_set_y(ui_about_text, 40);
    lv_obj_set_align(ui_about_text, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_about_text,
                      "This is a personal project, the goal is to make an easy-to-use emulation and download tool.");
    lv_obj_set_style_text_font(ui_about_text, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
