// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: rts_link

#include "../ui.h"

void ui_daplink_screen_screen_init(void)
{
    ui_daplink_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_daplink_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_daplink_screen, &ui_img_image_tree_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container1 = lv_obj_create(ui_daplink_screen);
    lv_obj_remove_style_all(ui_container1);
    lv_obj_set_width(ui_container1, lv_pct(100));
    lv_obj_set_height(ui_container1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_container1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rxd1 = lv_label_create(ui_container1);
    lv_obj_set_width(ui_rxd1, 10);
    lv_obj_set_height(ui_rxd1, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_rxd1, "RXD0");
    lv_obj_set_style_text_font(ui_rxd1, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gnd2 = lv_label_create(ui_container1);
    lv_obj_set_width(ui_gnd2, 10);
    lv_obj_set_height(ui_gnd2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gnd2, 12);
    lv_obj_set_y(ui_gnd2, 0);
    lv_label_set_text(ui_gnd2, "GND");
    lv_obj_set_style_text_font(ui_gnd2, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txd1 = lv_label_create(ui_container1);
    lv_obj_set_width(ui_txd1, 10);
    lv_obj_set_height(ui_txd1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txd1, 24);
    lv_obj_set_y(ui_txd1, 0);
    lv_label_set_text(ui_txd1, "TXD0");
    lv_obj_set_style_text_font(ui_txd1, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rts1 = lv_label_create(ui_container1);
    lv_obj_set_width(ui_rts1, 10);
    lv_obj_set_height(ui_rts1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rts1, 50);
    lv_obj_set_y(ui_rts1, 0);
    lv_label_set_text(ui_rts1, "CDC TX");
    lv_obj_set_style_text_font(ui_rts1, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dtr1 = lv_label_create(ui_container1);
    lv_obj_set_width(ui_dtr1, 10);
    lv_obj_set_height(ui_dtr1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dtr1, 62);
    lv_obj_set_y(ui_dtr1, 0);
    lv_label_set_text(ui_dtr1, "CDC RX");
    lv_obj_set_style_text_font(ui_dtr1, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nc4 = lv_label_create(ui_container1);
    lv_obj_set_width(ui_nc4, 10);
    lv_obj_set_height(ui_nc4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nc4, 74);
    lv_obj_set_y(ui_nc4, 0);
    lv_label_set_text(ui_nc4, "nRESET");
    lv_obj_set_style_text_font(ui_nc4, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gnd3 = lv_label_create(ui_container1);
    lv_obj_set_width(ui_gnd3, 10);
    lv_obj_set_height(ui_gnd3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gnd3, 120);
    lv_obj_set_y(ui_gnd3, 0);
    lv_label_set_text(ui_gnd3, "GND");
    lv_obj_set_style_text_font(ui_gnd3, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vcc1 = lv_label_create(ui_container1);
    lv_obj_set_width(ui_vcc1, 10);
    lv_obj_set_height(ui_vcc1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vcc1, 132);
    lv_obj_set_y(ui_vcc1, 0);
    lv_label_set_text(ui_vcc1, "3V3");
    lv_obj_set_style_text_font(ui_vcc1, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nc5 = lv_label_create(ui_container1);
    lv_obj_set_width(ui_nc5, 10);
    lv_obj_set_height(ui_nc5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nc5, 144);
    lv_obj_set_y(ui_nc5, 0);
    lv_label_set_text(ui_nc5, "SWDIO");
    lv_obj_set_style_text_font(ui_nc5, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nc6 = lv_label_create(ui_container1);
    lv_obj_set_width(ui_nc6, 10);
    lv_obj_set_height(ui_nc6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nc6, 158);
    lv_obj_set_y(ui_nc6, 0);
    lv_label_set_text(ui_nc6, "SWCLK");
    lv_obj_set_style_text_font(ui_nc6, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
