// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: rts_link

#include "../ui.h"

void ui_logo_screen_screen_init(void)
{
    ui_logo_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_logo_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_logo = lv_img_create(ui_logo_screen);
    lv_img_set_src(ui_logo, &ui_img_image_logo_png);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
