// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: rts_link

#include "../ui.h"

void ui_menu_screen_screen_init(void)
{
    ui_menu_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_menu_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_menu_screen, &ui_img_image_tree_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roller_menu = lv_roller_create(ui_menu_screen);
    lv_roller_set_options(ui_roller_menu, "DAP Link\nOffline Link\nUSB To Uart\nUSB Storage\nFiles\nSettings\nAbout",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_roller_menu, lv_pct(100));
    lv_obj_set_height(ui_roller_menu, lv_pct(100));
    lv_obj_set_align(ui_roller_menu, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_roller_menu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_roller_menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_roller_menu, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_roller_menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roller_menu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roller_menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_roller_menu, lv_color_hex(0xFFFF00), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_roller_menu, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_roller_menu, &ui_font_RobotoMedium28, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_roller_menu, 7, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roller_menu, lv_color_hex(0x2C0F9D), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roller_menu, 100, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_roller_menu, LV_GRAD_DIR_VER, LV_PART_SELECTED | LV_STATE_DEFAULT);

}
