// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: rts_link

#include "../ui.h"

void ui_offlink_download_screen_screen_init(void)
{
    ui_offlink_download_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_offlink_download_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_offlink_download_screen, &ui_img_image_tree_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_file_name = lv_label_create(ui_offlink_download_screen);
    lv_obj_set_width(ui_file_name, lv_pct(100));
    lv_obj_set_height(ui_file_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_file_name, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_file_name, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_file_name, "File Name");
    lv_obj_set_style_text_align(ui_file_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_file_name, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_success = lv_label_create(ui_offlink_download_screen);
    lv_obj_set_width(ui_success, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_success, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_success, 5);
    lv_obj_set_y(ui_success, 25);
    lv_label_set_text(ui_success, "Success: 256");
    lv_obj_set_style_text_font(ui_success, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_failure = lv_label_create(ui_offlink_download_screen);
    lv_obj_set_width(ui_failure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_failure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_failure, 5);
    lv_obj_set_y(ui_failure, 45);
    lv_label_set_text(ui_failure, "Failure: 21");
    lv_obj_set_style_text_font(ui_failure, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status = lv_label_create(ui_offlink_download_screen);
    lv_obj_set_width(ui_status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_status, 0);
    lv_obj_set_y(ui_status, 32);
    lv_obj_set_align(ui_status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_status, "Success");
    lv_obj_set_style_text_font(ui_status, &ui_font_RobotoMedium28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_status, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_status, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_status, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_status, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_status, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

}
