// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: rts_link

#include "../ui.h"

void ui_offlink_setting_screen_screen_init(void)
{
    ui_offlink_setting_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_offlink_setting_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_offlink_setting_screen, &ui_img_image_tree_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_title = lv_label_create(ui_offlink_setting_screen);
    lv_obj_set_width(ui_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_title, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_title, "Select Firmware");
    lv_obj_set_style_text_font(ui_title, &ui_font_RobotoMedium22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roller_files = lv_roller_create(ui_offlink_setting_screen);
    lv_roller_set_options(ui_roller_files, "File 1\nFile 2\nFile 3\nFile 4\nFile 5", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_roller_files, 100);
    lv_obj_set_width(ui_roller_files, lv_pct(100));
    lv_obj_set_align(ui_roller_files, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_roller_files, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roller_files, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roller_files, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_roller_files, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_roller_files, lv_color_hex(0xFFFF00), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_roller_files, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_roller_files, &ui_font_RobotoMedium22, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_roller_files, 7, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roller_files, lv_color_hex(0x2C0F9D), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roller_files, 100, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_roller_files, LV_GRAD_DIR_VER, LV_PART_SELECTED | LV_STATE_DEFAULT);

}
