// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: rts_link

#include "../ui.h"

void ui_usb_uart_screen_screen_init(void)
{
    ui_usb_uart_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_usb_uart_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_usb_uart_screen, &ui_img_image_tree_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container3 = lv_obj_create(ui_usb_uart_screen);
    lv_obj_remove_style_all(ui_container3);
    lv_obj_set_width(ui_container3, lv_pct(100));
    lv_obj_set_height(ui_container3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_container3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rxd = lv_label_create(ui_container3);
    lv_obj_set_width(ui_rxd, 10);
    lv_obj_set_height(ui_rxd, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_rxd, "RXD");
    lv_obj_set_style_text_font(ui_rxd, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gnd = lv_label_create(ui_container3);
    lv_obj_set_width(ui_gnd, 10);
    lv_obj_set_height(ui_gnd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gnd, 10);
    lv_obj_set_y(ui_gnd, 0);
    lv_label_set_text(ui_gnd, "GND");
    lv_obj_set_style_text_font(ui_gnd, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txd = lv_label_create(ui_container3);
    lv_obj_set_width(ui_txd, 10);
    lv_obj_set_height(ui_txd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txd, 20);
    lv_obj_set_y(ui_txd, 0);
    lv_label_set_text(ui_txd, "TXD");
    lv_obj_set_style_text_font(ui_txd, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rts = lv_label_create(ui_container3);
    lv_obj_set_width(ui_rts, 10);
    lv_obj_set_height(ui_rts, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rts, 50);
    lv_obj_set_y(ui_rts, 0);
    lv_label_set_text(ui_rts, "RTS");
    lv_obj_set_style_text_font(ui_rts, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dtr = lv_label_create(ui_container3);
    lv_obj_set_width(ui_dtr, 10);
    lv_obj_set_height(ui_dtr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dtr, 60);
    lv_obj_set_y(ui_dtr, 0);
    lv_label_set_text(ui_dtr, "DTR");
    lv_obj_set_style_text_font(ui_dtr, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nc1 = lv_label_create(ui_container3);
    lv_obj_set_width(ui_nc1, 10);
    lv_obj_set_height(ui_nc1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nc1, 70);
    lv_obj_set_y(ui_nc1, 0);
    lv_label_set_text(ui_nc1, "N C");
    lv_obj_set_style_text_font(ui_nc1, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gnd1 = lv_label_create(ui_container3);
    lv_obj_set_width(ui_gnd1, 10);
    lv_obj_set_height(ui_gnd1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gnd1, 120);
    lv_obj_set_y(ui_gnd1, 0);
    lv_label_set_text(ui_gnd1, "GND");
    lv_obj_set_style_text_font(ui_gnd1, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vcc = lv_label_create(ui_container3);
    lv_obj_set_width(ui_vcc, 10);
    lv_obj_set_height(ui_vcc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vcc, 130);
    lv_obj_set_y(ui_vcc, 0);
    lv_label_set_text(ui_vcc, "3V3");
    lv_obj_set_style_text_font(ui_vcc, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nc2 = lv_label_create(ui_container3);
    lv_obj_set_width(ui_nc2, 10);
    lv_obj_set_height(ui_nc2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nc2, 140);
    lv_obj_set_y(ui_nc2, 0);
    lv_label_set_text(ui_nc2, "N C");
    lv_obj_set_style_text_font(ui_nc2, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nc3 = lv_label_create(ui_container3);
    lv_obj_set_width(ui_nc3, 10);
    lv_obj_set_height(ui_nc3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nc3, 150);
    lv_obj_set_y(ui_nc3, 0);
    lv_label_set_text(ui_nc3, "N C");
    lv_obj_set_style_text_font(ui_nc3, &ui_font_RobotoRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
