// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: rts_link

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_logo_screen
void ui_logo_screen_screen_init(void);
lv_obj_t * ui_logo_screen;
lv_obj_t * ui_logo;


// SCREEN: ui_menu_screen
void ui_menu_screen_screen_init(void);
lv_obj_t * ui_menu_screen;
lv_obj_t * ui_roller_menu;


// SCREEN: ui_about_screen
void ui_about_screen_screen_init(void);
lv_obj_t * ui_about_screen;
lv_obj_t * ui_about_title;
lv_obj_t * ui_about_text;


// SCREEN: ui_offlink_setting_screen
void ui_offlink_setting_screen_screen_init(void);
lv_obj_t * ui_offlink_setting_screen;
lv_obj_t * ui_title;
lv_obj_t * ui_roller_files;


// SCREEN: ui_offlink_download_screen
void ui_offlink_download_screen_screen_init(void);
lv_obj_t * ui_offlink_download_screen;
lv_obj_t * ui_file_name;
lv_obj_t * ui_success;
lv_obj_t * ui_failure;
lv_obj_t * ui_status;


// SCREEN: ui_usb_uart_screen
void ui_usb_uart_screen_screen_init(void);
lv_obj_t * ui_usb_uart_screen;
lv_obj_t * ui_container3;
lv_obj_t * ui_rxd;
lv_obj_t * ui_gnd;
lv_obj_t * ui_txd;
lv_obj_t * ui_rts;
lv_obj_t * ui_dtr;
lv_obj_t * ui_nc1;
lv_obj_t * ui_gnd1;
lv_obj_t * ui_vcc;
lv_obj_t * ui_nc2;
lv_obj_t * ui_nc3;


// SCREEN: ui_daplink_screen
void ui_daplink_screen_screen_init(void);
lv_obj_t * ui_daplink_screen;
lv_obj_t * ui_container1;
lv_obj_t * ui_rxd1;
lv_obj_t * ui_gnd2;
lv_obj_t * ui_txd1;
lv_obj_t * ui_rts1;
lv_obj_t * ui_dtr1;
lv_obj_t * ui_nc4;
lv_obj_t * ui_gnd3;
lv_obj_t * ui_vcc1;
lv_obj_t * ui_nc5;
lv_obj_t * ui_nc6;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_logo_screen_screen_init();
    ui_menu_screen_screen_init();
    ui_about_screen_screen_init();
    ui_offlink_setting_screen_screen_init();
    ui_offlink_download_screen_screen_init();
    ui_usb_uart_screen_screen_init();
    ui_daplink_screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_logo_screen);
}
