// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: rts_link

#ifndef _RTS_LINK_UI_H
#define _RTS_LINK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_logo_screen
void ui_logo_screen_screen_init(void);
extern lv_obj_t * ui_logo_screen;
extern lv_obj_t * ui_logo;
// SCREEN: ui_menu_screen
void ui_menu_screen_screen_init(void);
extern lv_obj_t * ui_menu_screen;
extern lv_obj_t * ui_roller_menu;
// SCREEN: ui_about_screen
void ui_about_screen_screen_init(void);
extern lv_obj_t * ui_about_screen;
extern lv_obj_t * ui_about_title;
extern lv_obj_t * ui_about_text;
// SCREEN: ui_offlink_setting_screen
void ui_offlink_setting_screen_screen_init(void);
extern lv_obj_t * ui_offlink_setting_screen;
extern lv_obj_t * ui_title;
extern lv_obj_t * ui_roller_files;
// SCREEN: ui_offlink_download_screen
void ui_offlink_download_screen_screen_init(void);
extern lv_obj_t * ui_offlink_download_screen;
extern lv_obj_t * ui_file_name;
extern lv_obj_t * ui_success;
extern lv_obj_t * ui_failure;
extern lv_obj_t * ui_status;
// SCREEN: ui_usb_uart_screen
void ui_usb_uart_screen_screen_init(void);
extern lv_obj_t * ui_usb_uart_screen;
extern lv_obj_t * ui_container3;
extern lv_obj_t * ui_rxd;
extern lv_obj_t * ui_gnd;
extern lv_obj_t * ui_txd;
extern lv_obj_t * ui_rts;
extern lv_obj_t * ui_dtr;
extern lv_obj_t * ui_nc1;
extern lv_obj_t * ui_gnd1;
extern lv_obj_t * ui_vcc;
extern lv_obj_t * ui_nc2;
extern lv_obj_t * ui_nc3;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_image_logo_png);    // assets/image/logo.png
LV_IMG_DECLARE(ui_img_image_tree_png);    // assets/image/tree.png



LV_FONT_DECLARE(ui_font_RobotoLight93);
LV_FONT_DECLARE(ui_font_RobotoMedium22);
LV_FONT_DECLARE(ui_font_RobotoMedium28);
LV_FONT_DECLARE(ui_font_RobotoRegular16);
LV_FONT_DECLARE(ui_font_RobotoRegular38);
LV_FONT_DECLARE(ui_font_RobotoRegular58);
LV_FONT_DECLARE(ui_font_RobotoRegular65);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
